apiVersion: apps/v1
kind: Deployment
metadata:
 name: webserver-dep
 labels:
   app: webserver
 namespace: webserver
spec:
 replicas: 3
 selector:
   matchLabels:
     app: webserver
 template:
   metadata:
     labels:
       app: webserver
   spec:
     containers:
       - name: webserver
         image: sibibalu/webserver:webserver
         ports:
           - containerPort: 80
