apiVersion: v1
kind: Service
metadata:
 name: webserver-svc
 labels:
   app: webserver
 namespace: webserver
spec:
 type: NodePort
 ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 80
 selector:
    app: webserver
